#:import get_color_from_hex kivy.utils.get_color_from_hex

<Intro_Screen>:
    MDFloatLayout:
        FitImage:
            source: './logo.jpeg'
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}

        MDFillRoundFlatIconButton:
            icon: "pencil"
            text: "Start"
            size_hint_x: 0.15
            pos_hint: {'center_x': 0.5, 'center_y': 0.72}
            theme_text_color: "Custom"
            text_color: 0, 0, 0, 1
            md_bg_color: "#f5c242"
            md_bg_color: 0.92, 0.83, 0.78, 0.5
            on_release: root.release_action()

<User_Input>:
    size_hint_y: None
    height: dp(60)
    size_hint_x: 0.4
    adaptive_height: True
    pos_hint: {'center_x': 0.8}
    MDScreen:
        md_bg_color: app.theme_cls.primary_color
        radius: dp(25)
        MDLabel:
            id: user_input
            text: root.text
            color: 0, 0, 0, 1
            font_size: root.font_size
            valigh: "middle"
            halign: "center"

<Bot_Response>:
    size_hint_y: None
    height: dp(60)
    size_hint_x: 0.4
    adaptive_height: True
    pos_hint: {'center_x': 0.2}
    MDScreen:
        md_bg_color: "f59e42" 
        radius: dp(25)
        MDLabel:
            id: bot_response
            text: root.text
            color: 0, 0, 0, 1
            font_size: root.font_size
            valigh: "middle"
            halign: "center"

<Chat>:
    MDBoxLayout:
        orientation: 'vertical'
        spacing: dp(20)

        MDTopAppBar:
            title: "GPT2-ChatApp"
            orientation: "horizontal"
            
            MDIconButton:
                id: music_button
                icon: "speaker-pause"
                on_release: root.stop_music()

            MDIconButton:
                icon: "skip-next-circle"
                on_release: root.next_music()

        MDBoxLayout:
            size_hint_y: None
            height: dp(40)

        ScrollView:
            id: chat_scroll_view

            MDBoxLayout:
                id: chat_area
                adaptive_height: True
                orientation: "vertical"
                padding: dp(20)
                spacing: dp(12)

        MDBoxLayout:
            size_hint_y: None
            height: dp(50)
            padding: dp(40)
            spacing: dp(10)

            MDTextField:
                id: user_message
                hint_text: "Type your message..."
                font_style: "Caption"
                multiline: True
                mode: "round"
                max_text_length: 1024
                helper_text: "Massage"
                size_hint_x: 0.85
                color: 0, 0, 0, 1
                
            MDFillRoundFlatIconButton:
                icon: "send"
                text: "send"
                size_hint_x: 0.15
                on_press: root.send_message()
                on_release: root.bot_response()



