#:import get_color_from_hex kivy.utils.get_color_from_hex

<Intro_Screen>:
    MDFloatLayout:
        FitImage:
            source: './logo.jpeg'
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}

        MDFillRoundFlatIconButton:
            icon: "pencil"
            text: "Start"
            size_hint_x: 0.15
            pos_hint: {'center_x': 0.5, 'center_y': 0.72}
            theme_text_color: "Custom"
            text_color: 0, 0, 0, 1
            md_bg_color: "#f5c242"
            md_bg_color: 0.92, 0.83, 0.78, 0.5
            on_release: root.release_action()

<User_Input>:
    size_hint_y: None
    height: dp(60)
    size_hint_x: 0.4
    adaptive_height: True
    pos_hint: {'center_x': 0.8}
    MDScreen:
        md_bg_color: app.theme_cls.primary_color
        radius: dp(25)
        MDLabel:
            id: user_input
            text: root.text
            color: 0, 0, 0, 1
            font_size: root.font_size
            valigh: "middle"
            halign: "center"

<Bot_Response>:
    size_hint_y: None
    height: dp(60)
    size_hint_x: 0.4
    adaptive_height: True
    pos_hint: {'center_x': 0.25}
    MDScreen:
        md_bg_color: "f59e42" 
        radius: dp(25)
        MDLabel:
            id: bot_response
            text: root.text
            color: 0, 0, 0, 1
            font_size: root.font_size
            valigh: "middle"
            halign: "center"

<Chat>:
    MDBoxLayout:
        orientation: 'vertical'

        MDTopAppBar:
            title: 'GPT-2 Chat'
            orientation: "horizontal"
            
            MDIconButton:
                id: music_button
                icon: "speaker-pause"
                on_release: root.stop_music()

            MDIconButton:
                icon: "skip-next-circle"
                on_release: root.next_music()

        FloatLayout:
            orientation: 'horizontal'

            ScrollView:
                id: chat_scroll_view
                size_hint_x: 1.0

                MDBoxLayout:
                    id: chat_area
                    adaptive_height: True
                    orientation: "vertical"
                    spacing: dp(12)
                    padding: [dp(50), dp(20), dp(20), dp(20)]

            MDBoxLayout:
                size_hint_x: None
                width: dp(56)
                orientation: 'vertical'
                pos_hint: {'center_y': 1.0}
                spacing: dp(10)
                padding: [dp(10), dp(10), dp(10), dp(0)]

                MDFloatingActionButton:
                    id: menu_button
                    icon: "layers-triple"
                    on_release: root.menu.open()

                MDFloatingActionButton:
                    icon: "delete"
                    on_release: root.del_chat()

                MDFloatingActionButton:
                    icon: "plus-circle"
                    on_release: root.new_chat()

        MDBoxLayout:
            size_hint_y: None
            height: dp(50)
            padding: dp(40)
            spacing: dp(10)

            MDTextField:
                id: user_message
                hint_text: "Type your message..."
                font_style: "Caption"
                multiline: True
                mode: "round"
                max_text_length: 1024
                helper_text: "Massage"
                size_hint_x: 0.85
                color: 0, 0, 0, 1
                
            MDFillRoundFlatIconButton:
                icon: "send"
                text: "send"
                size_hint_x: 0.15
                on_press: root.send_message()
                on_release: root.bot_response()



