#:import get_color_from_hex kivy.utils.get_color_from_hex

<User_Input>:
    size_hint_y: None
    height: dp(60)
    size_hint_x: 0.4
    adaptive_height: True
    pos_hint: {'center_x': 0.8}
    MDScreen:
        md_bg_color: app.theme_cls.primary_color
        radius: dp(25)
        MDLabel:
            id: user_input
            text: root.text
            color: 1,1,1,1
            font_size: root.font_size
            valigh: "middle"
            halign: "center"

<Bot_Response>:
    size_hint_y: None
    height: dp(60)
    size_hint_x: 0.4
    adaptive_height: True
    pos_hint: {'center_x': 0.2}
    MDScreen:
        md_bg_color: get_color_from_hex("#474747")
        radius: dp(25)
        MDLabel:
            id: bot_response
            text: root.text
            color: 1,1,1,1
            font_size: root.font_size
            valigh: "middle"
            halign: "center"

<Chat>:
    MDBoxLayout:
        orientation: 'vertical'
        spacing: dp(20)

        MDTopAppBar:
            title: "GPT2-ChatApp"
            left_action_items: [["robot"]]

        MDBoxLayout:
            size_hint_y: None
            height: dp(40)

            MDLabel:
                text: "Hey, I'm here for you."
                color: 0, 0, 0, 0.5
                font_style: "Caption"
                valigh: "middle"
                halign: "center"

        ScrollView:
            id: chat_scroll_view

            MDBoxLayout:
                id: chat_area
                adaptive_height: True
                orientation: "vertical"
                padding: dp(20)
                spacing: dp(12)

        MDBoxLayout:
            size_hint_y: None
            height: dp(50)
            padding: dp(40)
            spacing: dp(10)

            MDTextField:
                id: user_message
                hint_text: "Type your message..."
                font_style: "Caption"
                multiline: True
                mode: "round"
                max_text_length: 1024
                helper_text: "Massage"
                size_hint_x: 0.85
                
            MDFillRoundFlatIconButton:
                icon: "send"
                text: "send"
                size_hint_x: 0.15
                on_press: root.send_message()
                on_release: root.bot_response()



